### ISSUE TITLE
slf4j canot cast to logback

### ISSUE THREAD

**Issue by zqhxuyuan** [aaronp/multi-project#1]
I notice you have anotation on web dependency, I try to add play dependency on web project
and there are errors when I try to run play

```
[MyProject-web] $ run

java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:80)
	at play.api.libs.logback.LogbackLoggerConfigurator.init(LogbackLoggerConfigurator.scala:26)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:94)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:207)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:73)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:73)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:99)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:52)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last web/compile:run for the full output.
[error] (web/compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 1 s, completed 2017-3-8 20:27:10
```

**Comment by zqhxuyuan** [comment]
solve the problem. 

```
  excludeDependencies ++= Seq(
    SbtExclusionRule("org.slf4j", "slf4j-simple"),
    SbtExclusionRule("org.slf4j", "slf4j-api"),
    SbtExclusionRule("org.slf4j", "slf4j-jdk12")
  )
```

**Comment by aaronp** [comment]
Thanks! I'll put that in ... cheers
